### ISSUE TITLE
Build Failed while running the ./gradlew loadAverages  step

### ISSUE THREAD

**Issue by JaideepKatkar** [pivotalsoftware/gfxd-demo#2]
Hi I am using Pivotal Single Node Cluster PIVHDSNE_VMWARE_VM-2.1.0-75 while running the demo
I encountered the the below error while running the  ./gradlew loadAverages

[pivhdsne:gfxd-demo]$ ./gradlew loadAverages
Creating properties on demand (a.k.a. dynamic properties) has been deprecated and is scheduled to be removed in Gradle 2.0. Please read http://gradle.org/docs/current/dsl/org.gradle.api.plugins.ExtraPropertiesExtension.html for information on the replacement for dynamic properties.
Deprecated dynamic property: "jobClassName" on "project ':gfxd-demo-mapreduce'", value: "com.pivotal.gfxd.demo....".
:schema
gfxd> -- DROPs in order
drop table if exists load_averages_shadow;
0 rows inserted/updated/deleted
gfxd> drop asynceventlistener if exists AggListener;
0 rows inserted/updated/deleted
gfxd> drop table if exists load_averages;
0 rows inserted/updated/deleted
gfxd> drop table if exists raw_sensor;
0 rows inserted/updated/deleted
gfxd> drop hdfsstore if exists sensorStore;
0 rows inserted/updated/deleted
gfxd> drop function if exists expired;
0 rows inserted/updated/deleted
gfxd> create function expired (timestamp bigint, age integer)
  returns integer
  language java
  parameter style java
  no sql
  external name 'com.pivotal.gfxd.demo.ExpirationPredicate.expired';
0 rows inserted/updated/deleted
gfxd> -- CREATES in order
 create hdfsstore sensorStore
  NameNode 'hdfs://localhost:8020'
  HomeDir '/sensorStore'
  BatchSize 10
  BatchTimeInterval 2000
  WriteOnlyFileRolloverInterval 60;
ERROR 42X01: SQLSTATE=42X01,SEVERITY=-1: (Server=localhost[1529],Thread[DRDAConnThread_20,5,gemfirexd.daemons]) Syntax error: Encountered "WriteOnlyFileRolloverInterval" at line 6, column 3.
Was expecting one of:
    "days" ...
    "hours" ...
    "minutes" ...
    "seconds" ...
    "milliseconds" ...
    .
Caused by: SqlException: SQLSTATE=42X01,SEVERITY=-1: (Server=localhost[1529],Thread[DRDAConnThread_20,5,gemfirexd.daemons]) Syntax error: Encountered "WriteOnlyFileRolloverInterval" at line 6, column 3.
Was expecting one of:
    "days" ...
    "hours" ...
    "minutes" ...
    "seconds" ...
    "milliseconds" ...
    .
    at com.pivotal.gemfirexd.internal.client.am.Statement.completeSqlca(Statement.java:2034)
Exception in thread "main" java.lang.RuntimeException: Problem starting run.
    at com.gemstone.gemfire.internal.GemFireUtilLauncher.invoke(GemFireUtilLauncher.java:182)
    at com.pivotal.gemfirexd.tools.GfxdUtilLauncher.invoke(GfxdUtilLauncher.java:228)
    at com.pivotal.gemfirexd.tools.GfxdUtilLauncher.main(GfxdUtilLauncher.java:160)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.gemstone.gemfire.internal.GemFireUtilLauncher.invoke(GemFireUtilLauncher.java:167)
    ... 2 more
Caused by: FatalException: 42X01: SQLSTATE=42X01,SEVERITY=-1: (Server=localhost[1529],Thread[DRDAConnThread_20,5,gemfirexd.daemons]) Syntax error: Encountered "WriteOnlyFileRolloverInterval" at line 6, column 3.
Was expecting one of:
    "days" ...
    "hours" ...
    "minutes" ...
    "seconds" ...
    "milliseconds" ...
    .
    at com.pivotal.gemfirexd.internal.impl.tools.ij.utilMain.handleSQLException(utilMain.java:836)
    at com.pivotal.gemfirexd.internal.impl.tools.ij.utilMain.doCatch(utilMain.java:735)
    at com.pivotal.gemfirexd.internal.impl.tools.ij.utilMain.runScriptGuts(utilMain.java:430)
    at com.pivotal.gemfirexd.internal.impl.tools.ij.utilMain.goScript(utilMain.java:297)
    at com.pivotal.gemfirexd.tools.internal.MiscTools$1.executeCommand(MiscTools.java:134)
    at com.pivotal.gemfirexd.tools.internal.ToolsBase.invoke(ToolsBase.java:119)
    at com.pivotal.gemfirexd.tools.internal.MiscTools.main(MiscTools.java:80)
    ... 7 more
:schema FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':schema'.
> Process 'command '/usr/lib/gphd/gfxd/bin/gfxd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.424 secs

**Comment by JaideepKatkar** [comment]
I think I figured it out.... the syntax in the sql script should include { MILLISECONDS | SECONDS | MINUTES | HOURS | DAYS } in BatchTimeInterval and WriteOnlyFileRolloverInterval

create hdfsstore sensorStore
NameNode 'hdfs://localhost:8020'
HomeDir '/sensorStore'
BatchSize 10
BatchTimeInterval 2000
WriteOnlyFileRolloverInterval 60;

**Comment by jdeppe-pivotal** [comment]
Glad you got sorted out. Could you send a pull request for the fix?
